# Generated by Django 5.0.6 on 2024-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(default=True),
        ),
    ]
