# Generated by Django 5.0.6 on 2024-05-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_order_is_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirm',
        ),
    ]
