# Generated by Django 5.0.6 on 2024-06-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_order_is_confirmed_order_items_order_suborders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='suborders',
        ),
    ]
