# Generated by Django 5.0.6 on 2024-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_order_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(db_default=True, default=False),
        ),
    ]
