# Generated by Django 5.0.6 on 2024-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_order_items_remove_order_suborders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='suborders',
            field=models.JSONField(default=list),
        ),
    ]
