# Generated by Django 5.0.6 on 2024-05-31 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_order_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.item'),
        ),
    ]
