# Generated by Django 5.0.6 on 2024-05-31 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_item_price_alter_suborder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.item'),
        ),
    ]
