# Generated by Django 5.0.6 on 2024-05-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_suborder_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_confirm',
            new_name='is_confirmed',
        ),
    ]
